service: lambda-cpuinfo

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
package:
  exclude:
    - scripts/**
    - docs/**
functions:

  cpu128:
    memorySize: 128
    handler: handler.getcpu
    events:
      - http: GET /cpu128

  cpu3008:
    memorySize: 3008
    handler: handler.getcpu
    events:
      - http: GET /cpu3008

  cpu3009:
    memorySize: 3009
    handler: handler.getcpu
    events:
      - http: GET /cpu3009

  cpu5307:
    memorySize: 5307
    handler: handler.getcpu
    events:
      - http: GET /cpu5307

  cpu5308:
    memorySize: 5308
    handler: handler.getcpu
    events:
      - http: GET /cpu5308

  cpu7076:
    memorySize: 7076
    handler: handler.getcpu
    events:
      - http: GET /cpu7076

  cpu7077:
    memorySize: 7077
    handler: handler.getcpu
    events:
      - http: GET /cpu7077

  cpu8845:
    memorySize: 8845
    handler: handler.getcpu
    events:
      - http: GET /cpu8845

  cpu8846:
    memorySize: 8846
    handler: handler.getcpu
    events:
      - http: GET /cpu8846

  cpu10240:
    memorySize: 10240
    handler: handler.getcpu
    events:
      - http: GET /cpu10240

plugins:
  - serverless-python-requirements