service: lambda-cpu-alloc

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

functions:
  process_small:
    memorySize: 1792
    handler: handler.getcpu
    events:
      - http: GET /small

  process_medium:
    memorySize: 3584
    handler: handler.getcpu
    events:
      - http: GET /medium1

  process_threshold:
    memorySize: 3585
    handler: handler.getcpu
    events:
      - http: GET /medium2
  process_threshold:
    memorySize: 10000
    handler: handler.getcpu
    events:
      - http: GET /large
plugins:
  - serverless-python-requirements
