service: lambda-cpuinfo

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

functions:
  cpu1:
    memorySize: 1792
    handler: handler.getcpu
    events:
      - http: GET /cpu1

  cpu2:
    memorySize: 3584
    handler: handler.getcpu
    events:
      - http: GET /cpu2

  cpu2plus:
    memorySize: 3585
    handler: handler.getcpu
    events:
      - http: GET /cpu2plus

  cpu3:
    memorySize: 5377
    handler: handler.getcpu
    events:
      - http: GET /cpu3

  cpu4:
    memorySize: 7169
    handler: handler.getcpu
    events:
      - http: GET /cpu4

  cpu5:
    memorySize: 8961
    handler: handler.getcpu
    events:
      - http: GET /cpu5

  max:
    memorySize: 10240
    handler: handler.getcpu
    events:
      - http: GET /max
plugins:
  - serverless-python-requirements
